# Site settings
course_name: Computer Networks
course_description: "This course offers an in-depth exploration of computer networks, adopting a top-down approach to present the fundamental concepts and principles. Beginning with application-layer protocols, such as HTTP, FTP, and DNS, the course progressively delves into transport, network, and link-layer mechanisms, including TCP/IP, routing algorithms, and data link technologies. Through this approach, students will gain a holistic understanding of how the Internet functions, from high-level applications to low-level data transmission.<br /> <br /> 

Topics covered include network architecture, packet-switching and circuit-switching,  congestion control, software-defined networks, and wireless networks. The course also emphasizes practical applications of networking concepts through hands-on lab work and problem-solving exercises.<br /> <br /> 

By the end of the course, students will have a comprehensive understanding of both theoretical and practical aspects of modern computer networks, preparing them for advanced study or careers in network administration, cybersecurity, and cloud computing."
course_semester: "Fall 2024"

baseurl: "/cn-2024" # the subpath of your site, e.g. /blog/
url: "https://huangqy89.github.io/" # the base hostname & protocol for your site

schoolname: "Sun Yat-sen University"
schoolurl: "https://sysu.edu.cn"
# twitter_username: huangqy89

address: |
    No.132 Outer Ring East Road,
    Guangzhou Higher Education Mega Center,
    Guangzhou

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false
    experiments:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"

repository: huangqy89/cn-2024
