# Site settings
course_name: Digital Circuits & Logic Design
course_description: "This undergraduate course introduces the fundamental principles of digital circuits and logic design, providing students with a strong foundation in the analysis and design of digital systems. Topics include Boolean algebra, combinational and sequential logic design, and the implementation of logic circuits using basic gates and flip-flops. <br /> <br />

Through hands-on labs, students will gain practical experience in designing, building, and testing digital circuits using breadboards, logic analyzers, and other tools. The course also explores real-world applications of digital logic in computing and embedded systems, preparing students for advanced studies and careers in electrical and computer engineering."

course_semester: "Spring 2025"

baseurl: "/dc-2025" # the subpath of your site, e.g. /blog/
url: "https://huangqy89.github.io/" # the base hostname & protocol for your site

schoolname: "Sun Yat-sen University"
schoolurl: "https://sysu.edu.cn"
# twitter_username: huangqy89

address: |
    No.132 Outer Ring East Road,
    Guangzhou Higher Education Mega Center,
    Guangzhou

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false
    laboratories:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  - scope:
      path: ""
      type: "laboratory"
    values:
      layout: "laboratories"

repository: huangqy89/dc-2025
